#!/bin/bash

if pgrep -x "i3" > /dev/null
then
	echo "Switching i3 -> kwin_x11"
	killall i3
	kwin_x11 &>/dev/null & 
else
	echo "Switching kwin_x11 -> i3"
	killall -q kwin_x11
	i3 & 2>&1 > /dev/null
fi
